import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
arr_add = arr + 5
print("Array after adding 5:", arr_add)
arr_mul = arr * 2
print("Array after multiplying by 2:", arr_mul)
arr_square = arr ** 2
print("Array after squaring each element:", arr_square)
arr_sum = np.sum(arr)
print("Sum of all elements:", arr_sum)
arr_mean = np.mean(arr)
print("Mean of all elements:", arr_mean)
arr_std = np.std(arr)
print("Standard deviation of all elements:", arr_std)
arr_reshaped = arr.reshape((1, 5))
print("Reshaped array (1x5):", arr_reshaped)
arr_transposed = arr_reshaped.T
print("Transposed array (5x1):", arr_transposed)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)
arr_2d_mul = np.dot(arr_2d, arr_2d.T)
print("Matrix multiplication result:\n", arr_2d_mul)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print("\nArray 1:", arr1)
print("Array 2:", arr2)
arr_add = np.add(arr1, arr2)
print("\nAddition of arrays:", arr_add)
arr_sub = np.subtract(arr2, arr1)
print("Subtraction of arrays:", arr_sub)
print("Multiplication of arrays:", arr_mul)
arr_div = np.divide(arr2, arr1)
print("Division of arrays:", arr_div)
arr_dot = np.dot(arr1, arr2)
print("\nDot product of arrays:", arr_dot)
arr_concat = np.concatenate((arr1, arr2))
print("\nConcatenation of arrays:", arr_concat)
arr_reshaped = np.reshape(arr_concat, (2, 4))
print("\nReshaped array (2x4):\n", arr_reshaped)
arr_transposed = np.transpose(arr_reshaped)
print("\nTransposed array (4x2):\n", arr_transposed)
max_element = np.max(arr1)
print("\nMaximum element in Array 1:", max_element)
min_element = np.min(arr2)
print("Minimum element in Array 2:", min_element)
sum_elements = np.sum(arr1)
print("Sum of elements in Array 1:", sum_elements)
mean_elements = np.mean(arr2)
print("Mean of elements in Array 2:", mean_elements)
arr_slice = arr_concat[2:6]
print("\nSliced array (from index 2 to 5):", arr_slice)